# Generated by Django 3.1.1 on 2020-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.IntegerField(),
        ),
    ]
